using System.Net.NetworkInformation;

try
{
    if (args is [ { Length: > 0 } host ])
    {
        var ping = new Ping();
        var options = new PingOptions { Ttl = 54 }; // Устанавливаем TTL = 54
        var reply = await ping.SendPingAsync(host, 1000, new byte[32], options); // Отправляем пинг с настройками
        // Generated by Copilot
        Console.WriteLine(reply.Status == IPStatus.Success 
            ? $"Ping successful, time: {reply.RoundtripTime}ms" 
            : "Ping failed");
    }
    else
    {
        Console.WriteLine("Please provide a host address.");
    }
}
catch (PingException ex)
{
    Console.WriteLine($"Ping failed: {ex.Message}");
}

Console.WriteLine("End.");
